const fs=require('fs'),vm=require('vm'),path=require('path');
const repo=process.argv[2]||path.resolve(__dirname,'..');
const fixture=process.argv[3];
if(!fixture) throw Error('Pass repository path and regression fixture viewer.html as arguments');
const script=fs.readFileSync(path.join(repo,'LogMapping/resources/index.html'),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
let passed=0,failed=0;const assert=(v,m='assertion failed')=>{if(!v)throw Error(m)};
function context(){
 const nodes={},created=[];
 function element(){const e={tagName:'DIV',style:{},dataset:{},classList:{toggle(){},add(){},remove(){},contains(){return false}},children:[],_events:{},isConnected:true,
 addEventListener(t,f){this._events[t]=f},setAttribute(k,v){this[k]=v},getAttribute(k){return this[k]??null},hasAttribute(k){return this[k]!=null},matches(){return false},querySelector(){return element()},querySelectorAll(){return[]},appendChild(x){this.children.push(x);if(x.id)nodes[x.id]=x},remove(){},focus(){},getBoundingClientRect(){return{left:0,bottom:0}},getClientRects(){return[{}]},innerHTML:'',textContent:'',value:''};created.push(e);return e}
 const doc={readyState:'loading',addEventListener(){},getElementById(id){return nodes[id]??=element()},querySelectorAll(){return[]},createElement:element,body:element(),activeElement:element()};
 let reply;const c={document:doc,console,alert(){},confirm(){return true},getComputedStyle(){return{display:'none'}},setTimeout(f,ms){if(ms===0)return 0;return setTimeout(f,ms).unref()},clearTimeout,requestAnimationFrame(){return 0},cancelAnimationFrame(){},addEventListener(){},chrome:{webview:{addEventListener(t,f){reply=f},postMessage(m){reply({data:{type:m.type+'Result',data:{id:m.id,success:true}}})}}}};
 c.window=c;vm.createContext(c);new vm.Script(script).runInContext(c);c.created=created;c.nodes=nodes;c.reply=(data)=>reply({data});return c;
}
async function test(name,fn){try{await fn();passed++;console.log('PASS '+name)}catch(e){failed++;console.log('FAIL '+name+': '+e.stack)}}
async function main(){
 await test('native error rejects and clears pending',async()=>{const c=context();c.chrome.webview.postMessage=m=>c.reply({type:m.type+'Result',data:{id:m.id,success:false,error:'disk full'}});let e;try{await c.callNative('writeFile',{})}catch(x){e=x}assert(e?.message==='disk full');assert(vm.runInContext('_pending.size',c)===0)});
 await test('catalog open does not prune or delete',async()=>{const c=context(),calls=[];c.callNative=async(t,p)=>{calls.push(t);return{content:JSON.stringify({drives:[{id:'old',dbId:1,num:1,name:'A',scannedPath:'E:\\'}]})}};c.dbCall=async(t,p)=>{calls.push(t);return{description:JSON.stringify({databaseId:'db1',drives:[{id:1,scanned_path:'E:\\'}]}),rowsJson:'[]'}};await c.loadFile('A.hcat');assert(c.catalog.drives.length===1);assert(!calls.includes('dbPrune')&&!calls.includes('dbDeleteDrive'))});
 await test('foreign database catalog rejected',async()=>{const c=context();let error;c.showErrDetail=e=>error=e;c.callNative=async()=>({content:JSON.stringify({databaseId:'foreign',drives:[]})});c.dbCall=async()=>({description:JSON.stringify({databaseId:'local',drives:[]})});await c.loadFile('foreign.hcat');assert(error?.includes('다른 DB'));assert(c.currentFilePath===null)});
 await test('failed save leaves dirty and propagates failure',async()=>{const c=context();c._databaseInfo={databaseId:'db'};c.currentFilePath='test.hcat';c.markDirty(true);c.callNative=async()=>{throw Error('disk full')};let threw=false;try{await c.persistCatalog()}catch{threw=true}assert(threw&&c.isDirty)});
 await test('save-as preserves edits made during write',async()=>{const c=context();c._databaseInfo={databaseId:'db'};let finish;c.callNative=async(t)=>t==='saveFileDialog'?{path:'copy.hcat'}:new Promise(r=>finish=r);const job=c.saveAsNewFile();for(let i=0;i<10&&!finish;i++)await Promise.resolve();assert(finish);c.markDirty(true);finish({success:true});await job;assert(c.isDirty&&c.currentFilePath==='copy.hcat')});
 await test('close retries a previously failed write',async()=>{const c=context();c._databaseInfo={databaseId:'db'};c.currentFilePath='test.hcat';c.markDirty(true);c.callNative=async()=>{throw Error('disk full')};try{await c.persistCatalog()}catch{}let wrote=false,ready;c.callNative=async()=>{wrote=true;return{success:true}};c.chrome.webview.postMessage=m=>ready=m;await c.finishClosing();assert(wrote&&!c.isDirty&&ready.content==='ok')});
 await test('rapid catalog switch is blocked during pending load',async()=>{const c=context();let release;const calls=[];c.callNative=async(t,p)=>{calls.push(p.path);return new Promise(r=>release=r)};c.dbCall=async()=>({description:JSON.stringify({databaseId:'db',drives:[]})});const first=c.loadFile('first.hcat');await Promise.resolve();await c.loadFile('second.hcat');assert(calls.length===1);release({content:'{"drives":[]}'});await first;assert(c.currentFilePath==='first.hcat'&&!c._catalogLoading)});
 await test('duplicate references rejected before changing catalog',async()=>{const c=context();let error;c.showErrDetail=e=>error=e;c.callNative=async()=>({content:JSON.stringify({drives:[{dbId:1,num:1,name:'A'},{dbId:1,num:2,name:'B'}]})});c.dbCall=async()=>({description:JSON.stringify({databaseId:'db',drives:[{id:1}]})});await c.loadFile('bad.hcat');assert(error?.includes('중복')&&c.currentFilePath===null)});
 await test('new mutations blocked while closing and abort restores access',async()=>{const c=context();c._closingForExit=true;let wrote=false;c.dbCall=async()=>{wrote=true};await c.setItemColor(1,'x','#red');assert(!wrote);c.reply({type:'windowCloseAborted',data:{}});assert(!c._closingForExit)});
 await test('malformed tags rejected without replacing active catalog',async()=>{const c=context();let error;c.showErrDetail=e=>error=e;c.callNative=async()=>({content:JSON.stringify({drives:[{num:1,name:'A',tags:'bad'}]})});c.dbCall=async()=>({description:JSON.stringify({databaseId:'db',drives:[]})});await c.loadFile('bad.hcat');assert(error?.includes('태그')&&c.currentFilePath===null)});
 await test('fresh save never uses shared my_drives.hcat',async()=>{const c=context();c.DATA_DIR='X:\\data';c._databaseInfo={databaseId:'db'};let written;c.callNative=async(t,p)=>{written=p.path;return{success:true}};await c.persistCatalog();assert(written.includes('catalog-')&&!written.includes('my_drives.hcat'))});
 await test('cross-drive context tag targets result owner',async()=>{const c=context();c.selectedDrive={dbId:1};const calls=[];c.dbCall=async(t,p)=>{calls.push(p);return{success:true}};c.renderCurrent=()=>{};c.showFlatCtxMenu({clientX:0,clientY:0},'2|photo.jpg','file','photo.jpg');const dot=c.created.find(e=>e.title&&e._events.click&&e.style.cssText.includes('width:18px'));assert(dot);dot._events.click({stopPropagation(){}});await Promise.resolve();assert(calls[0].driveId===2)});
 await test('search sends catalog/filter/sort before limit',async()=>{const c=context();c.catalog={drives:[{dbId:7}]};c.searchQuery='project/photo';c.filterCat='tag';c.filterTagColor='#red';c.sortMode='size-desc';let params;c.dbCall=async(t,p)=>{params=p;return{rowsJson:'[]'}};await c.renderSearch(c.document.createElement('div'));assert(params.driveIds[0]===7&&params.color==='#red'&&params.sort==='size-desc'&&params.limit===50001)});
 await test('stale search cannot overwrite a changed screen',async()=>{const c=context();c.catalog={drives:[{dbId:1}]};c.searchQuery='photo';let resolve,mounted=false;c.dbCall=()=>new Promise(r=>resolve=r);c.mountFlatList=()=>mounted=true;const job=c.renderSearch(c.document.createElement('div'));c._renderEpoch++;resolve({rowsJson:'[{"name":"photo"}]'});await job;assert(!mounted)});
 await test('tree size is valid CSS in large mode',()=>{const c=context();c.viewMode='large';const row=c.buildRow({node:{name:'photo.jpg',is_dir:0,size:1,full_path:'photo.jpg'},depth:0,key:'1|photo.jpg'});assert(row.innerHTML.includes('font-size:24px')&&!row.innerHTML.includes('pxpx'))});
 await test('copy resolves root of owning drive',()=>{const c=context();c.catalog={drives:[{dbId:1,scannedPath:'E:\\'},{dbId:2,scannedPath:'F:\\'}]};assert(c.copyPathFor(2,'project/photo.jpg')==='F:\\project\\photo.jpg')});
 await test('no-scan form initialized with tag/color choices',()=>{const c=context();c.catalog={drives:[]};c.goStep2NoScan();assert(c.nodes['tag-row'].innerHTML.includes('tag-opt'));assert(c.nodes['color-row'].innerHTML.includes('color-dot'));assert(c.nodes['inp-name'].value==='')});
 await test('database errors do not turn into empty results',()=>{const c=context();let threw=false;try{c.dbRows({error:'broken'})}catch{threw=true}assert(threw)});
 const viewer=fs.readFileSync(fixture,'utf8'),vc=context();vc.DecompressionStream=function(){};vc.setTimeout=f=>{f();return 0};
 for(const m of viewer.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(m[1]).runInContext(vc);
 await test('viewer reserved names and newline paths',()=>{const tree=vc.buildTree('D'+JSON.stringify('constructor')+'\nF'+JSON.stringify('constructor/child.txt')+'\nF'+JSON.stringify('line\nbreak.txt')+'\n');assert(tree.c.constructor.f[0]==='child.txt'&&tree.f[0]==='line\nbreak.txt')});
 await test('viewer scans every drive and preserves later exact hit',async()=>{vc.DRIVES=Array.from({length:12},(_,i)=>({i,n:i+1}));vc.curText=null;let visited=[];vc.inflate=async i=>{visited.push(i);return Array.from({length:410},(_,j)=>'F'+JSON.stringify(i===11&&j===409?'photo':'photo-'+i+'-'+j+'.jpg')).join('\n')};const hits=await vc.searchAll('photo');assert(visited.length===12&&hits.total===4920);assert(hits[0].di===11&&hits[0].n==='photo');assert(hits.length<=1000)});
 await test('viewer cancels obsolete search before later drives',async()=>{vc.curText=null;vc._seq=101;let visits=0;vc.inflate=async()=>{visits++;vc._seq=102;return 'F"photo.jpg"\n'};const hits=await vc.searchAll('photo',101);assert(visits===1&&hits.length===0)});
 await test('scan crossing backup size threshold updates visible notice',()=>{const c=context();c._databaseInfo={databaseId:'db',autoBackupSkipped:false};c.reply({type:'dbScanResult',data:{autoBackupSkipped:true}});assert(c._databaseInfo.autoBackupSkipped&&c.nodes['storage-note'].textContent.includes('대용량'))});
 console.log(`RESULT passed=${passed} failed=${failed}`);process.exitCode=failed?1:0;
}
main().catch(e=>{console.error(e);process.exitCode=1});
